spring:
  application:
    name: listing-app
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
  show-actuator: true